// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mt_backend.Data;

#nullable disable

namespace mt_backend.Migrations
{
    [DbContext(typeof(MiniTaskerDbContext))]
    [Migration("20251015094550_SeedErrorLogs")]
    partial class SeedErrorLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("mt_backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("mt_backend.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "Initial error log entry",
                            Source = "System",
                            StackTrace = "Stack trace goes here",
                            Timestamp = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(746)
                        },
                        new
                        {
                            Id = 2,
                            Message = "Another error log entry",
                            Source = "Application",
                            StackTrace = "Another stack trace",
                            Timestamp = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(748)
                        });
                });

            modelBuilder.Entity("mt_backend.Models.Subtask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Subtasks");
                });

            modelBuilder.Entity("mt_backend.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = 1,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2577),
                            Description = "First task",
                            DueDate = new DateTime(2025, 10, 22, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2577),
                            Status = 0,
                            Title = "Sample Task",
                            UpdatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2577)
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = 2,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2585),
                            Description = "Second task",
                            DueDate = new DateTime(2025, 10, 22, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2585),
                            Status = 1,
                            Title = "Sample Task 2",
                            UpdatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2585)
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2587),
                            Description = "Third task",
                            DueDate = new DateTime(2025, 10, 22, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2588),
                            Status = 2,
                            Title = "Sample Task 3",
                            UpdatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2587)
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = 4,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Fourth task",
                            DueDate = new DateTime(2025, 10, 22, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2590),
                            Status = 1,
                            Title = "Sample Task 4",
                            UpdatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2590)
                        },
                        new
                        {
                            Id = 5,
                            AssignedTo = 5,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2592),
                            Description = "Fifth task",
                            DueDate = new DateTime(2025, 10, 22, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2593),
                            Status = 0,
                            Title = "Sample Task 5",
                            UpdatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2592)
                        },
                        new
                        {
                            Id = 6,
                            AssignedTo = 1,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2595),
                            Description = "sixth task",
                            DueDate = new DateTime(2025, 10, 22, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2595),
                            Status = 1,
                            Title = "Sample Task 6",
                            UpdatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(2595)
                        });
                });

            modelBuilder.Entity("mt_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AzureAdId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(619),
                            Email = "alice@example.com",
                            Name = "Alice",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(620),
                            Email = "bob@example.com",
                            Name = "Bob",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(622),
                            Email = "anne@example.com",
                            Name = "Anne",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(623),
                            Email = "peter@example.com",
                            Name = "Peter",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 15, 9, 45, 49, 857, DateTimeKind.Utc).AddTicks(624),
                            Email = "jenny@example.com",
                            Name = "Jenny",
                            Password = "hashed-password-1"
                        });
                });

            modelBuilder.Entity("mt_backend.Models.Comment", b =>
                {
                    b.HasOne("mt_backend.Models.TaskItem", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mt_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mt_backend.Models.Subtask", b =>
                {
                    b.HasOne("mt_backend.Models.TaskItem", "Task")
                        .WithMany("Subtasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("mt_backend.Models.TaskItem", b =>
                {
                    b.HasOne("mt_backend.Models.User", "AssignedUser")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("mt_backend.Models.TaskItem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("mt_backend.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
