// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mt_backend.Data;

#nullable disable

namespace mt_backend.Migrations
{
    [DbContext(typeof(MiniTaskerDbContext))]
    [Migration("20250820094035_AddComments")]
    partial class AddComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mt_backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("mt_backend.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = 1,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7919),
                            Description = "First task",
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Sample Task",
                            UpdatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7919)
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = 2,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7921),
                            Description = "Second task",
                            DueDate = new DateTime(2025, 8, 27, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7922),
                            Status = 1,
                            Title = "Sample Task 2",
                            UpdatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7922)
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = 3,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7929),
                            Description = "Third task",
                            DueDate = new DateTime(2025, 8, 27, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7930),
                            Status = 2,
                            Title = "Sample Task 3",
                            UpdatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7930)
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = 4,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7932),
                            Description = "Fourth task",
                            DueDate = new DateTime(2025, 8, 27, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7933),
                            Status = 1,
                            Title = "Sample Task 4",
                            UpdatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7932)
                        },
                        new
                        {
                            Id = 5,
                            AssignedTo = 5,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7954),
                            Description = "Fifth task",
                            DueDate = new DateTime(2025, 8, 27, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7955),
                            Status = 0,
                            Title = "Sample Task 5",
                            UpdatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7955)
                        },
                        new
                        {
                            Id = 6,
                            AssignedTo = 1,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7957),
                            Description = "sixth task",
                            DueDate = new DateTime(2025, 8, 27, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7958),
                            Status = 1,
                            Title = "Sample Task 6",
                            UpdatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(7957)
                        });
                });

            modelBuilder.Entity("mt_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(6166),
                            Email = "alice@example.com",
                            Name = "Alice",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(6168),
                            Email = "bob@example.com",
                            Name = "Bob",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(6169),
                            Email = "anne@example.com",
                            Name = "Anne",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(6215),
                            Email = "peter@example.com",
                            Name = "Peter",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 20, 9, 40, 34, 906, DateTimeKind.Utc).AddTicks(6221),
                            Email = "jenny@example.com",
                            Name = "Jenny",
                            Password = "hashed-password-1"
                        });
                });

            modelBuilder.Entity("mt_backend.Models.Comment", b =>
                {
                    b.HasOne("mt_backend.Models.TaskItem", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mt_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mt_backend.Models.TaskItem", b =>
                {
                    b.HasOne("mt_backend.Models.User", "AssignedUser")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("mt_backend.Models.TaskItem", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("mt_backend.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
