// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mt_backend.Data;

#nullable disable

namespace mt_backend.Migrations
{
    [DbContext(typeof(MiniTaskerDbContext))]
    [Migration("20250829115539_InitialCreateAndSeeding")]
    partial class InitialCreateAndSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("mt_backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("mt_backend.Models.Subtask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Subtasks");
                });

            modelBuilder.Entity("mt_backend.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4555),
                            Description = "First task",
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Sample Task",
                            UpdatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4556)
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4561),
                            Description = "Second task",
                            DueDate = new DateTime(2025, 9, 5, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4562),
                            Status = 1,
                            Title = "Sample Task 2",
                            UpdatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4562)
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4574),
                            Description = "Third task",
                            DueDate = new DateTime(2025, 9, 5, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4576),
                            Status = 2,
                            Title = "Sample Task 3",
                            UpdatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4575)
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4580),
                            Description = "Fourth task",
                            DueDate = new DateTime(2025, 9, 5, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4582),
                            Status = 1,
                            Title = "Sample Task 4",
                            UpdatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4581)
                        },
                        new
                        {
                            Id = 5,
                            AssignedTo = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4586),
                            Description = "Fifth task",
                            DueDate = new DateTime(2025, 9, 5, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4587),
                            Status = 0,
                            Title = "Sample Task 5",
                            UpdatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4587)
                        },
                        new
                        {
                            Id = 6,
                            AssignedTo = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4591),
                            Description = "sixth task",
                            DueDate = new DateTime(2025, 9, 5, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4593),
                            Status = 1,
                            Title = "Sample Task 6",
                            UpdatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 428, DateTimeKind.Utc).AddTicks(4592)
                        });
                });

            modelBuilder.Entity("mt_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 427, DateTimeKind.Utc).AddTicks(9598),
                            Email = "alice@example.com",
                            Name = "Alice",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 427, DateTimeKind.Utc).AddTicks(9603),
                            Email = "bob@example.com",
                            Name = "Bob",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 427, DateTimeKind.Utc).AddTicks(9606),
                            Email = "anne@example.com",
                            Name = "Anne",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 427, DateTimeKind.Utc).AddTicks(9609),
                            Email = "peter@example.com",
                            Name = "Peter",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 11, 55, 38, 427, DateTimeKind.Utc).AddTicks(9612),
                            Email = "jenny@example.com",
                            Name = "Jenny",
                            Password = "hashed-password-1"
                        });
                });

            modelBuilder.Entity("mt_backend.Models.Comment", b =>
                {
                    b.HasOne("mt_backend.Models.TaskItem", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mt_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mt_backend.Models.Subtask", b =>
                {
                    b.HasOne("mt_backend.Models.TaskItem", "Task")
                        .WithMany("Subtasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("mt_backend.Models.TaskItem", b =>
                {
                    b.HasOne("mt_backend.Models.User", "AssignedUser")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("mt_backend.Models.TaskItem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("mt_backend.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
